apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodereds.digvijay17jluy
spec:
  group: digvijay17jluy
  names:
    kind: Nodered
    listKind: NoderedList
    plural: nodereds
    singular: nodered
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Nodered is the Schema for the nodereds API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: NoderedSpec defines the desired state of Nodered
            type: object
          status:
            description: NoderedStatus defines the observed state of Nodered
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
